#!/usr/bin/env bash
# redirect to 301 permanent

sudo apt-get update
sudo apt-get -y install nginx
# Listen on port 80
sudo ufw allow 'Nginx HTTP'
# create page with the string Holberton School and start nginx
echo "Holberton School" > /var/www/html/index.html
# set redirection
sed -i "/listen 80 default_server;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
service nginx reload
