#!/usr/bin/env bash
# Creates file containing own pid and change default response actions of signals
sudo touch /var/run/holbertonscript.pid
sudo chmod 666 /var/run/holbertonscript.pid
echo $BASHPID >> /var/run/holbertonscript.pid
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
    trap "echo I hate the kill command" SIGTERM
    trap "echo Y U no love me?!" SIGINT
    trap "rm /var/run/holbertonscript.pid" SIGQUIT, SIGTERM
done
