#!/usr/bin/env bash
# Tell story from passwd file
file="/etc/passwd"
IFS=:
while IFS=: read -r USERNAME HOME_DIRECTORY USER_ID GROUP_ID COMMAND_SHELL PASSWORD USER_ID_INFO
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "$file"
