#!/usr/bin/env bash
# Block all incoming traffic except port 22, 443 and 80

#Deny all incoming connections
sudo ufw default deny incoming
# Enable the above ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
#Enable firewall
sudo ufw enable
